### ISSUE TITLE
/currency-codes/r/codes-all.json not available 

### ISSUE THREAD

**Issue by frieman** [datasets/currency-codes#9]
When trying to get the currency code using: http://data.okfn.org/data/core/currency-codes/r/codes-all.json
You get an error message:
"An error occurred in the application and your page could not be served. Please try again in a few moments.
If you are the application owner, check your logs for details."

The CSV endpoint works
Thanks

**Comment by rgrp** [comment]
WORKSFORME. I just tested this and works fine for me so please retry. Please re-open if this persists.
